name: Deploy TCIOE CMS
on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Build & Deploy
    runs-on: [self-hosted, club]
    env:
      VITE_APP_VERSION: ${{ secrets.VITE_APP_VERSION }}
      GENERATE_SOURCEMAP: ${{ secrets.GENERATE_SOURCEMAP }}
      VITE_TURNSTILE_SITE_KEY: ${{ secrets.VITE_TURNSTILE_SITE_KEY }}

      VITE_PUBLIC_APP_HTTP_SCHEME: ${{ secrets.VITE_PUBLIC_APP_HTTP_SCHEME }}
      VITE_PUBLIC_APP_BASE_URL: ${{ secrets.VITE_PUBLIC_APP_BASE_URL }}
      VITE_PUBLIC_APP_API_VERSION: ${{ secrets.VITE_PUBLIC_APP_API_VERSION }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Unified VPS Deployer
        run: |
          cd /srv/deployer
          node deploy.js $GITHUB_REPOSITORY
